# Generated by Django 3.2.20 on 2023-08-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testomonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='product',
            field=models.CharField(default='Unknown Product', max_length=100),
        ),
    ]
